url: "https://krivachy.xyz" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Tamás Kriváchy's academic website" # the name of your site, e.g. ACME Corp.
description: "Postdoc researcher @ ICFO, Barcelona" # a short description of site's purpose
