menu:
- {name: 'publications', url: '/publications'}
- {name: 'teaching', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Kvantum cirkáló', link: 'https://medium.com/kvantumcirkalo'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}

supervision:
- {name: 'Lorenzo Caramelli', location: 'ICFO', type: 'MSc thesis', year: '2025'}
- {name: 'Ían Paton Vazquez', location: 'ICFO', type: 'BSc Internship', year: '2025'}
- {name: 'Matías Víner', location: 'ICFO', type: 'BSc thesis', year: '2024'}
- {name: 'Martin Kerschbaumer', location: 'TU Wien, ICFO', type: 'MSc semester project, MSc thesis', year: '2023-2024'}
- {name: 'Javier Esteras Maza', location: 'TU Wien', type: 'BSc thesis', year: '2021'}
- {name: 'Antoine Girardin', location: 'University of Geneva', type: 'MSc thesis', year: '2020-2021'}

social:
- {icon: 'github', link: 'https://github.com/tkrivachy'}
- {icon: 'google', link: 'https://scholar.google.com/citations?hl=en&user=lYcJXqoAAAAJ'}
- {icon: 'twitter', link: 'https://twitter.com/KrivachyTamas'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/tamás-kriváchy-36370673/'}

contacts:
- {name: 'Tamás Kriváchy', title: 'postdoc', department: 'Quantum Information Theory', institution: 'ICFO - Institut de Ciencies Fotoniques (The Institute of Photonic Sciences)', institution_address: 'Av. Carl Friedrich Gauss, 3, 08860 Castelldefels (Barcelona), Spain', email: 'firstname.lastname@gmail.com (no accents)', image: 'assets/img/contact.jpg'}
