menu:
- {name: 'publications', url: '/publications'}
- {name: 'teaching', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#people:
#- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Kvantum cirkáló', link: 'https://medium.com/kvantumcirkalo'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}

social:
- {icon: 'github', link: 'https://github.com/tkrivachy'}
- {icon: 'twitter', link: 'https://twitter.com/KrivachyTamas'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/tamás-kriváchy-36370673/'}
- {icon: 'mastadon', link: 'https://qubit-social.xyz/@KrivachyTamas'}

contacts:
- {name: 'Tamás Kriváchy', title: 'postdoc', department: 'Quantum Information and Thermodynamics ', institution: 'Atominstitut, TU Wien', institution_address: 'Stadionallee 2, 1020 Wien, Austria', email: 'firstname.lastname@gmail.com (no accents)', image: 'assets/img/contact.jpg'}
